In [163]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [164]:
#Carga de un archivo .xlsx desde un libro con varias p√°ginas 
df= pd.read_excel('Gastos y costos 20-23.xlsx', sheet_name = '2023', skiprows=3)
df

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripci√≥n,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,NaN,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,NaN,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,NaN,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [165]:
#Identificar valores nulos por columna
valores_nulos= df.isnull().sum()
valores_nulos

Fecha            0
Folio           13
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [166]:
#Identificar valores nulos por dataframe
valores_nulos=df.isnull().sum().sum()
valores_nulos

np.int64(675)

In [167]:
#Realizamos una copia del dataframe
df1 = df.copy()

In [168]:
#Quinto m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df1["Folio"]=df1["Folio"].fillna(method="ffill")

C:\Users\sammm\AppData\Local\Temp\ipykernel_624\1765622335.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1["Folio"]=df1["Folio"].fillna(method="ffill")

In [169]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [170]:
#Cuarto m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por un string en  concreto 
df1["TIPO GASTO"] =df1["TIPO GASTO"].fillna("No registrado")

In [171]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [172]:
#Tercer m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por un valor num√©rico en  concreto 
df1["FP"]= df1["FP"].fillna(00) 
df1

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripci√≥n,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,0.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,0.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,NaN,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,NaN,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,NaN,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,0.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [173]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripci√≥n      0
MP              71
FP               0
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [174]:
#Cuarto m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por un string en  concreto 
df1["MP"] =df1["MP"].fillna("Pago")

In [175]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripci√≥n      0
MP               0
FP               0
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [176]:
#Sexto m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por valores no nulos hacia atr√°s backward fill" ("bfill")
#Filtro por columnas
df1["Poliza"] =df1["Poliza"].fillna(method="bfill")

C:\Users\sammm\AppData\Local\Temp\ipykernel_624\4049845603.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1["Poliza"] =df1["Poliza"].fillna(method="bfill")

In [177]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripci√≥n      0
MP               0
FP               0
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza           8
dtype: int64

In [178]:
#Cuarto m√©todo de sustituci√≥n de valores nulos
#Sustituir valores nulos por un string en  concreto 
df1["Poliza"] =df1["Poliza"].fillna("Pue")

In [181]:
#Corroboramos valores nulos
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha          0
UUID           0
RFC            0
Proveedor      0
Descripci√≥n    0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
dtype: int64

In [179]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
df1= df.dropna(axis=1)
df1

,Fecha,UUID,RFC,Proveedor,Descripci√≥n,TC,Importe,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,Tipo,Status
0,2023-01-01,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,Pago,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente
1,2023-01-01,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,Pago,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente
2,2023-01-01,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,1.0,5551.38,888.22,0.0,0.0,6439.60,6439.60,I,Vigente
3,2023-01-01,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,1.0,5551.98,888.32,0.0,0.0,6440.30,6440.30,I,Vigente
4,2023-01-01,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,1.0,8454.37,1352.70,0.0,0.0,9807.07,9807.07,I,Vigente
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente
393,2023-02-01,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,Epura 20 Lts Policarbonato,1.0,220.00,0.00,0.0,0.0,220.00,220.00,I,Vigente
394,2023-02-01,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,SERVICIOS BANCARIOS,1.0,18071.52,682.40,0.0,0.0,18753.92,18753.92,I,Vigente
395,2023-02-01,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14472.32,0.00,0.0,0.0,14472.32,14472.32,I,Vigente
396,2023-02-01,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,Pago,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente

In [180]:
#Identificar valores nulos por columna
valores_nulos=df1.isnull().sum()
valores_nulos

Fecha          0
UUID           0
RFC            0
Proveedor      0
Descripci√≥n    0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
dtype: int64

In [183]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        397 non-null    datetime64[ns]
 1   Folio        384 non-null    object
 2   UUID         397 non-null    object
 3   RFC          397 non-null    object
 4   Proveedor    397 non-null    object
 5   TIPO GASTO   389 non-null    object
 6   Descripci√≥n  397 non-null    object
 7   MP           326 non-null    object
 8   FP           326 non-null    float64
 9   TC           397 non-null    float64
 10  Importe      397 non-null    float64
 11  IVA          397 non-null    float64
 12  RET ISR      397 non-null    float64
 13  RET IVA      397 non-null    float64
 14  Otros        0 non-null      float64
 15  TOTAL MX     397 non-null    float64
 16  TOTAL SAT    397 non-null    float64
 17  Tipo         397 non-null    object
 18  Status       397 non-null    object
 19  Poliza       282 non-null    object
dtypes: datetime64[ns](1), float64(9), object(10)
memory usage: 62.2+ KB

In [184]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        397 non-null    datetime64[ns]
 1   UUID         397 non-null    object
 2   RFC          397 non-null    object
 3   Proveedor    397 non-null    object
 4   Descripci√≥n  397 non-null    object
 5   TC           397 non-null    float64
 6   Importe      397 non-null    float64
 7   IVA          397 non-null    float64
 8   RET ISR      397 non-null    float64
 9   RET IVA      397 non-null    float64
 10  TOTAL MX     397 non-null    float64
 11  TOTAL SAT    397 non-null    float64
 12  Tipo         397 non-null    object
 13  Status       397 non-null    object
dtypes: datetime64[ns](1), float64(7), object(6)
memory usage: 43.6+ KB

In [187]:
#Convertir DataFrame a xlsx
df1.to_csv("gastos_costos_correcto.csv")